"""empty message

Revision ID: 4b489e77c65d
Revises: 
Create Date: 2023-03-09 22:26:03.955009

"""
from alembic import op
import sqlalchemy as sa
from blog.models.models import User, Author, Article
from blog.models.database import db
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '4b489e77c65d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    # ### end Alembic commands ###

    admin = User(username='admin1', email='admin1@example.com',first_name='Iv', last_name='Ivanov', password=generate_password_hash('admin'), is_staff=True)
    user1 = User(username='First', email='first@first.com', first_name='Petr', last_name='Petrov', password=generate_password_hash('admin'), is_staff=False)
    author1 = Author(user_id=2)
    article1 = Article(article_id=1, title="Django", text='Django - это бесплатный фреймворк для веб-приложений на языке Python. Он позволяет быстро и удобно создавать качественные и масштабируемые веб-приложения, используя множество готовых компонентов и библиотек.', author_id=1)
    db.session.add(article1)
    db.session.add(author1)
    db.session.add(user1)
    db.session.add(admin)
    db.session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('authors')
    op.drop_table('users')
    # ### end Alembic commands ###
